### Vehicle - List All Vehicles
GET http://localhost:3000/vehicle

### Vehicle - List Vehicle by ID
GET http://localhost:3000/vehicle/1

### Vehicle - Create Vehicle
POST http://localhost:3000/vehicle
Content-Type: application/json

{
  "brand": "Impreza",
  "chassis": "SDF897988SDG689SG",
  "model": "Subaro",
  "plate": "QDA6172",
  "reindeer": "83974589346",
  "year": 2025
}

### Vehicle - Update Vehicle
PATCH http://localhost:3000/vehicle/1
Content-Type: application/json

{
  "plate": "ABC321",
  "chassis": "1234567890",
  "reindeer": "1234567890",
  "model": "Model X",
  "brand": "Brand X",
  "year": 2020
}
### Vehicle - Delete Vehicle
DELETE http://localhost:3000/vehicle/1
